---
name: MQTT IO
version: dev
slug: mqtt-io
description: Expose GPIO modules and digital sensors via MQTT for remote control and monitoring.
url: https://github.com/itsib/addon-mqtt-io
codenotary: itsib.su@gmail.com
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
homeassistant_api: true
uart: true
gpio: true
privileged:
  - SYS_RAWIO
map:
  - config:rw
  - share:rw
  - ssl
devices:
  - /dev/gpiomem
options:
  configuration_file: /config/mqtt-io/configuration.yaml
schema:
  configuration_file: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
